site_name: MaLSAMi Documentation 
theme: readthedocs
plugins:
    - search

markdown_extensions:
        - smarty
        - toc:
              permalink: True
        - sane_lists

pages:
    - Home : 
        - 'Home' : 'index.md'
        - 'First Steps' : 'first-steps.md'
    - Analysis :
        - 'Requirements Analysis' : 'analysis/requirements-analysis.md'
        - 'Schedulability Analysis' : 'analysis/schedulability-analysis.md'
    - 'Machine Learning' :
        - 'Machine Learning' : 'machine-learning/machine-learning.md'
        - 'Shallow learning': 'machine-learning/shallow-learning/shallow-learning.md'
        - 'Deep Learning': 'machine-learning/deep-learning.md'
    - Genode : 'genode/genode.md'
    - Data Generation : 
        - 'Distributor' : 'data-generation/distributor.md'
        - 'Monitor' : 'data-generation/monitor.md'
        - 'Data Generation' : 'data-generation/datageneration.md'
        - 'Data Visualization' : 'data-generation/data-visualization.md'
    - About : 'about.md'
